version: "{branch}-{build}"
environment:
  global:
    PATCH_VER: 10
    HG_REV: 17eb680e191f
  matrix:
  - TARGET: x86
    BITS: 32
  - TARGET: x86_64
    BITS: 64
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - windows
image: Visual Studio 2013
install:
- cmd: C:\cygwin64\setup-x86_64.exe -qgnNdO -l C:\cygwin64\var\cache\setup -R c:\cygwin64 -s http://cygwin.mirror.constant.com -P make -P unzip -P zip
build_script:
- cmd: C:\cygwin64\bin\bash -e -l -c "mkdir /cygdrive/c/projects/frc-openjdk/build && cd /cygdrive/c/projects/frc-openjdk/build && wget http://hg.openjdk.java.net/jdk-updates/jdk10u/archive/${HG_REV}.zip && wget http://download.savannah.gnu.org/releases/freetype/freetype-2.5.3.tar.gz && tar -xzf freetype-2.5.3.tar.gz && unzip -q ${HG_REV}.zip && cd jdk10u-${HG_REV} && env JAVA_HOME=/cygdrive/c/Program\ Files/Java/jdk9 bash configure --with-version-patch=${PATCH_VER} --with-jvm-variants=server --with-freetype-src=/cygdrive/c/projects/frc-openjdk/build/freetype-2.5.3 --with-target-bits=${BITS} && make CONF=windows-${TARGET}-normal-server-release all && cd build/windows-${TARGET}-normal-server-release/images && zip -r /cygdrive/c/projects/frc-openjdk/jre-${TARGET}.zip jre && zip -r /cygdrive/c/projects/frc-openjdk/jdk-${TARGET}.zip jdk"
test: off
artifacts:
- path: jre-$(TARGET).zip
- path: jdk-$(TARGET).zip
deploy:
- provider: GitHub
  auth_token:
    secure: 9vEYpyGo8MTutVQyQTMECylYj87OoVNDLt0Jd7KuJK4DbyKs2VrGmVARDxLv6uR0
  artifact: /.*\.zip/
  on:
    branch: windows
    appveyor_repo_tag: true
