# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
    PATCH_VER: 13
    HG_REV: 8513ac27b651

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:

- powershell: |
    $ProgressPreference = 'SilentlyContinue'
    wget https://www.cygwin.com/setup-x86_64.exe -O "setup-x86_64.exe"
    .\setup-x86_64.exe -qgnNdO -l C:\cygwin64\var\cache\setup -R c:\cygwin64 -s http://cygwin.mirror.constant.com -P autoconf -P make -P unzip -P zip
  displayName: 'Install Cygwin'

- script:
    C:\cygwin64\bin\bash -e -l -c "mkdir /cygdrive/c/projects/frc-openjdk/build && cd /cygdrive/c/projects/frc-openjdk/build && wget http://hg.openjdk.java.net/jdk-updates/jdk11u/archive/${HG_REV}.zip && unzip -q ${HG_REV}.zip && cd jdk11u-${HG_REV} && env JAVA_HOME=/cygdrive/c/Program\ Files/Java/jdk10 bash configure --with-version-patch=${PATCH_VER} --with-jvm-variants=server --with-target-bits=${BITS} --disable-warnings-as-errors --with-extra-cxxflags=-Zc:sizedDealloc- && make CONF=windows-${TARGET}-normal-server-release jdk-image && cd build/windows-${TARGET}-normal-server-release/images && zip -r /cygdrive/c/projects/frc-openjdk/jdk-${TARGET}.zip jdk"
  displayName: "Build JDK"
